use anyhow::Result;
use clap::{Parser, Subcommand};
use reqwest::Method;
use reqwest::header::{HeaderName, HeaderValue};
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;
use std::str::FromStr;
use std::sync::Arc;

use crate::playbook_capnp::HttpMethod;
use crate::tcpdump::HttpRequest;

mod tcpdump;

pub mod playbook_capnp {
    include!(concat!(env!("OUT_DIR"), "/playbook_capnp.rs"));
}

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Extracts HTTP requests from a .pcap file and saves them in a .playbook file.
    Extract {
        /// Path to the .pcap file(s) to extract the HTTP requests from, usually captured via `tcpdump`.
        #[arg(required = true)]
        tcpdump: Vec<String>,
        /// Optional filter to only include requests whose URL contains the specified string.
        /// For example, `--filter "/route"` will only include requests to the `/route` endpoint.
        #[arg(short, long)]
        filter: Option<String>,
        /// Optional output file name. If not provided, the default name is equal to the input file name with the `.playbook` extension.
        #[arg(short, long)]
        output: Option<String>,
    },

    /// Sends the requests to the specified URL and measures the throughput, success rate and latency percentiles.
    Run {
        /// The URL to send the request to.
        /// Example: http://localhost:8002
        url: String,
        /// The playbook file in .playbook format, generated by the `extract` command.
        playbook: PathBuf,
        /// Maximum number of concurrent requests to send.
        #[arg(short, long, default_value = "128")]
        concurrency: u8,
        /// Additional HTTP headers to include with each request (format: "Name:Value").
        /// Useful if additional authentication is required.
        #[arg(short, long)]
        header: Vec<String>,
    },
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Extract {
            tcpdump,
            filter,
            output,
        } => extract(tcpdump, filter, output),
        Commands::Run {
            url,
            playbook,
            concurrency,
            header,
        } => run(url, playbook, concurrency as usize, header),
    }
}

fn extract(tcpdumps: Vec<String>, filter: Option<String>, output: Option<String>) {
    let output = output.unwrap_or_else(|| format!("{}.playbook", tcpdumps[0]));
    let mut requests = Vec::new();

    for tcpdump in tcpdumps {
        println!("Parsing {tcpdump}...");

        let reader = tcpdump::TcpDumpReader::new(&tcpdump).expect("Failed to open tcpdump file");
        let mut total = 0;
        for request in reader {
            if filter.as_ref().is_none_or(|f| request.uri.contains(f)) {
                requests.push(request);
            }
            total += 1;
        }

        println!("Parsed {total} HTTP requests from {tcpdump}");
    }
    println!("Total requests extracted: {}", requests.len());

    let file = File::create(output).expect("Failed to create capnp file");
    let mut writer = BufWriter::new(file);

    for r in requests {
        let mut message = capnp::message::Builder::new_default();
        let mut request_builder = message.init_root::<playbook_capnp::http_request::Builder>();
        request_builder.set_method(r.method);
        request_builder.set_uri(&r.uri);
        request_builder.set_body(&r.body);
        request_builder.set_headers(r.headers.as_ref()).unwrap();

        capnp::serialize_packed::write_message(&mut writer, &message)
            .expect("Failed to write capnp message to the playbook");
    }

    writer.flush().expect("Failed to flush playbook file");
}

#[tokio::main(flavor = "multi_thread", worker_threads = 8)]
async fn run(
    url: String,
    playbook: PathBuf,
    max_concurrency: usize,
    additional_headers: Vec<String>,
) {
    let mut file = File::open(playbook).expect("Failed to open playbook file");
    let mut reader = std::io::BufReader::new(&mut file);
    let mut requests = Vec::new();
    while let Ok(message) = capnp::serialize_packed::read_message(&mut reader, Default::default()) {
        let root = message
            .get_root::<playbook_capnp::http_request::Reader>()
            .expect("Bad file format - no `HttpRequest`");

        let request = HttpRequest {
            method: root.get_method().expect("Bad file format - no `method`"),
            uri: root
                .get_uri()
                .expect("Bad file format - no `uri`")
                .to_string()
                .unwrap()
                .into(),
            headers: root
                .get_headers()
                .expect("Bad file format - no `headers`")
                .iter()
                .map(|h| h.unwrap().to_string().unwrap().into())
                .collect(),
            body: root.get_body().expect("Bad file format - no `body`").into(),
        };

        requests.push(request);
    }

    let requests: Arc<[HttpRequest]> = Arc::from(requests);
    let additional_headers: Arc<[String]> = Arc::from(additional_headers);

    let client = reqwest::Client::new();

    // Try to send a single request to check if the server is up
    let _ = send_request(&client, &url, &requests[0], &additional_headers)
        .await
        .expect("Failed to send a test request");

    // Doing concurrent requests via spawning tasks allows us to
    // - gradually increase the number of concurrent requests without pauses, thus keeping the server warm
    // - utilize more than one thread/core to avoid bottlenecks with sending requests
    let concurrency_levels = [4, 6, 8, 12, 16, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 128];
    let mut tasks = Vec::new();
    let (results_tx, results_rx) = flume::unbounded::<Option<std::num::NonZeroU32>>();
    let mut measure_cold_start = true;
    for concurrency in concurrency_levels
        .into_iter()
        .take_while(|c| *c <= max_concurrency)
    {
        // Gradually increase number of concurrent requests
        for task_idx in tasks.len()..concurrency {
            let client = client.clone();
            let url = url.clone();
            let additional_headers = additional_headers.clone();
            let requests = requests.clone();
            let results_tx = results_tx.clone();

            tasks.push(tokio::spawn(async move {
                // Avoid duplicate requests by cycling through the requests array
                let requests = requests
                    .iter()
                    .cycle()
                    .skip(task_idx)
                    .step_by(max_concurrency);
                for r in requests {
                    let start = std::time::Instant::now();
                    let result = send_request(&client, &url, r, &additional_headers).await;

                    let elapsed_us = start.elapsed().as_micros();
                    let latency = if result.is_ok_and(|r| r.status().is_success()) {
                        Some(std::num::NonZeroU32::new(elapsed_us as u32).unwrap())
                    } else {
                        None
                    };

                    // Channel has been closed, stop sending results and exit the task
                    if results_tx.send(latency).is_err() {
                        break;
                    }
                }
            }));
        }

        // todo: remove copy&paste with logic below
        if measure_cold_start {
            measure_cold_start = false;

            let start = std::time::Instant::now();
            let mut successfull = 0;
            let mut total = 0;
            let mut latencies = Vec::new();
            let mut metric = Metric::default();
            while let Ok(latency) = results_rx.recv() {
                total += 1;
                if let Some(latency) = latency {
                    successfull += 1;
                    latencies.push(latency.get());
                }
                let elapsed = start.elapsed();
                if elapsed.as_secs() >= 5 {
                    metric.throughput = total as f64 / elapsed.as_secs_f64();
                    metric.success_rate = successfull as f64 / total as f64;
                    break;
                }
            }
            latencies.sort_unstable();
            metric.concurrency = concurrency as u16;
            metric.p50 = latencies[(latencies.len() as f64 * 0.50) as usize] as f64 / 1000.0;
            metric.p95 = latencies[(latencies.len() as f64 * 0.95) as usize] as f64 / 1000.0;
            metric.p99 = latencies[(latencies.len() as f64 * 0.99) as usize] as f64 / 1000.0;

            println!(
                "Cold start with concurrency {}: throughput {:.2}rps, success rate {:.2}, p50 {:.1}ms, p95 {:.1}ms, p99 {:.1}ms",
                metric.concurrency,
                metric.throughput,
                metric.success_rate,
                metric.p50,
                metric.p95,
                metric.p99
            );
        }

        // First 15s read all results and throw them away
        let start = std::time::Instant::now();
        while let Ok(_latency) = results_rx.recv() {
            if start.elapsed().as_secs() >= 15 {
                break;
            }
        }

        // Then read the results for 15s and count the success rate, throughput and p50, p95, p99 latency
        let start = std::time::Instant::now();
        let mut successfull = 0;
        let mut total = 0;
        let mut latencies = Vec::new();
        let mut metric = Metric::default();
        while let Ok(latency) = results_rx.recv() {
            total += 1;
            if let Some(latency) = latency {
                successfull += 1;
                latencies.push(latency.get());
            }
            let elapsed = start.elapsed();
            if elapsed.as_secs() >= 15 {
                metric.throughput = total as f64 / elapsed.as_secs_f64();
                metric.success_rate = successfull as f64 / total as f64;
                break;
            }
        }
        latencies.sort_unstable();
        metric.concurrency = concurrency as u16;
        metric.p50 = latencies[(latencies.len() as f64 * 0.50) as usize] as f64 / 1000.0;
        metric.p95 = latencies[(latencies.len() as f64 * 0.95) as usize] as f64 / 1000.0;
        metric.p99 = latencies[(latencies.len() as f64 * 0.99) as usize] as f64 / 1000.0;
        println!(
            "Concurrency {}: throughput {:.2}rps, success rate {:.2}, p50 {:.1}ms, p95 {:.1}ms, p99 {:.1}ms",
            metric.concurrency,
            metric.throughput,
            metric.success_rate,
            metric.p50,
            metric.p95,
            metric.p99
        );
    }

    // Close the channel to stop all tasks
    drop(results_tx);
    drop(results_rx);
    for t in tasks {
        t.await.expect("Task panicked");
    }
}

async fn send_request(
    client: &reqwest::Client,
    base_url: &str,
    request: &HttpRequest,
    additional_headers: &[String],
) -> Result<reqwest::Response, reqwest::Error> {
    let method = match request.method {
        HttpMethod::Get => Method::GET,
        HttpMethod::Post => Method::POST,
        HttpMethod::Put => Method::PUT,
        HttpMethod::Delete => Method::DELETE,
        HttpMethod::Head => Method::HEAD,
        HttpMethod::Options => Method::OPTIONS,
        HttpMethod::Patch => Method::PATCH,
        HttpMethod::Trace => Method::TRACE,
    };

    client
        .request(method, format!("{}{}", base_url, &request.uri)) // URI always starts with '/'
        .headers(
            request
                .headers
                .iter()
                .map(|s| s.as_ref())
                .chain(additional_headers.iter().map(String::as_str))
                .filter_map(|h| {
                    h.split_once(':').and_then(|(k, v)| {
                        Some((
                            HeaderName::from_str(k).ok()?,
                            HeaderValue::from_str(v).ok()?,
                        ))
                    })
                })
                .collect(),
        )
        .body(request.body.to_vec())
        .send()
        .await
}

#[derive(Default)]
struct Metric {
    concurrency: u16,
    throughput: f64,
    success_rate: f64,
    p50: f64,
    p95: f64,
    p99: f64,
}
