use anyhow::{Context, Result};
use base64::{Engine, engine::general_purpose::STANDARD as BASE64};
use clap::{Parser, Subcommand};
use reqwest::Method;
use reqwest::header::{HeaderName, HeaderValue};
use rustc_hash::FxHashMap;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;
use std::str::FromStr;
use std::sync::Arc;

use crate::playbook_capnp::HttpMethod;
use crate::tcpdump::HttpRequest;

mod tcpdump;

pub mod playbook_capnp {
    include!(concat!(env!("OUT_DIR"), "/playbook_capnp.rs"));
}

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Extracts HTTP requests from a .pcap file and saves them in a .playbook file.
    Extract {
        /// Path to the .pcap file(s) to extract the HTTP requests from, usually captured via `tcpdump`.
        /// Reads stdin if no file is provided.
        tcpdump: Vec<String>,
        /// Optional filter to only include requests whose URL contains the specified string.
        /// For example, `--filter "/route"` will only include requests to the `/route` endpoint.
        #[arg(short, long)]
        filter: Option<String>,
        /// Optional output file name. If not provided, the default name is equal to the input file
        /// name with the `.playbook` extension.
        #[arg(short, long)]
        output: Option<String>,
    },

    /// Sends every request in a playbook to the endpoint once, reporting errors.
    /// Useful as a sanity check to ensure all requests are handled correctly by the server.
    Probe {
        /// The URL to send the requests to.
        /// Example: http://localhost:8002
        url: String,
        /// The playbook file in .playbook format, generated by the `extract` command.
        playbook: PathBuf,
        /// Additional HTTP headers to include with each request (format: "Name:Value").
        /// Useful if additional authentication is required.
        #[arg(short, long)]
        header: Vec<String>,
        /// Number of requests to skip from the beginning of the playbook.
        #[arg(short, long, default_value = "0")]
        skip: usize,
        /// Number of concurrent requests to send.
        #[arg(short, long, default_value = "1")]
        concurrency: usize,
    },

    /// Sends the requests to the specified URL and measures the throughput, success rate and latency percentiles.
    Run {
        /// The URL to send the request to.
        /// Example: http://localhost:8002
        url: String,
        /// The playbook file in .playbook format, generated by the `extract` command.
        playbook: PathBuf,
        /// Maximum number of concurrent requests to send.
        #[arg(short, long, default_value = "128")]
        concurrency: u8,
        /// Additional HTTP headers to include with each request (format: "Name:Value").
        /// Useful if additional authentication is required.
        #[arg(short, long)]
        header: Vec<String>,
    },
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Extract {
            tcpdump,
            filter,
            output,
        } => extract(tcpdump, filter, output),
        Commands::Probe {
            url,
            playbook,
            header,
            skip,
            concurrency,
        } => probe(url, playbook, header, skip, concurrency),
        Commands::Run {
            url,
            playbook,
            concurrency,
            header,
        } => run(url, playbook, concurrency as usize, header),
    }
}

fn extract(tcpdumps: Vec<String>, filter: Option<String>, output: Option<String>) {
    let output = output.unwrap_or_else(|| {
        if tcpdumps.is_empty() || (tcpdumps.len() == 1 && tcpdumps[0] == "-") {
            "capture.playbook".to_string()
        } else {
            format!("{}.playbook", tcpdumps[0])
        }
    });

    let file = File::create(&output).expect("Failed to create capnp file");
    let mut writer = BufWriter::new(file);
    let mut request_count = 0;
    let mut request_per_uri = FxHashMap::default();

    if tcpdumps.is_empty() || (tcpdumps.len() == 1 && tcpdumps[0] == "-") {
        // UNIX convention to read from stdin if no file is provided:
        // `cat file.pcap | minigun extract --filter "/route" -o route.playbook`
        // `tcpdump -i any -w - | minigun extract --filter "/route" -o route.playbook`
        println!("Reading tcpdump from stdin...");
        let stdin = std::io::stdin();
        let reader = tcpdump::TcpDumpReader::new(stdin).expect("Failed to read tcpdump from stdin");
        for request in reader {
            if filter.as_ref().is_none_or(|f| request.uri.contains(f)) {
                write_request(&request, &mut writer)
                    .expect("Failed to write capnp message to the playbook");
                request_count += 1;
                request_per_uri
                    .entry(request.uri)
                    .and_modify(|c| *c += 1)
                    .or_insert(1);
            }
        }
    } else {
        for tcpdump in tcpdumps {
            println!("Reading tcpdump file {tcpdump}...");
            let file = File::open(&tcpdump).expect("Failed to open tcpdump file");
            let reader = tcpdump::TcpDumpReader::new(file).expect("Failed to read tcpdump file");
            for request in reader {
                if filter.as_ref().is_none_or(|f| request.uri.contains(f)) {
                    write_request(&request, &mut writer)
                        .expect("Failed to write capnp message to the playbook");
                    request_count += 1;
                    request_per_uri
                        .entry(request.uri)
                        .and_modify(|c| *c += 1)
                        .or_insert(1);
                }
            }
        }
    }

    writer.flush().expect("Failed to flush playbook file");

    println!("Total requests extracted: {}", request_count);
    for (uri, count) in request_per_uri {
        println!("{}: {}", uri, count);
    }
}

fn probe(
    url: String,
    playbook: PathBuf,
    additional_headers: Vec<String>,
    skip: usize,
    concurrency: usize,
) {
    let client = reqwest::ClientBuilder::new()
        .default_headers(parse_headers(additional_headers))
        .build()
        .expect("Client::new()");

    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("Failed to create tokio runtime");

    let abort = Arc::new(std::sync::atomic::AtomicBool::new(false));
    let channel_capacity = concurrency * 8;
    let (tx, rx) = flume::bounded::<(usize, HttpRequest)>(channel_capacity);

    // Reader thread: reads requests from file and pushes them into the channel.
    // Also prints progress based on approximate completed request count.
    let reader_handle = std::thread::spawn(move || {
        let file = File::open(&playbook).expect("Failed to open playbook file");
        let mut reader = std::io::BufReader::new(file);

        // Skip first `skip` requests
        for i in 0..skip {
            if read_request(&mut reader).is_err() {
                println!("[{i}] Failed to read request while skipping first {skip} requests.");
                return skip;
            }
        }

        let mut sent: usize = 0;
        let mut batch_start = std::time::Instant::now();
        let mut next_milestone: usize = skip + 1000;
        let mut index = skip;
        while let Ok(request) = read_request(&mut reader) {
            if tx.send((index, request)).is_err() {
                break;
            }
            sent += 1;
            index += 1;

            // Approximate completed = skip + sent - items still in channel
            let completed = skip + sent.saturating_sub(tx.len());
            if completed >= next_milestone {
                let rps = (completed - skip) as f64 / batch_start.elapsed().as_secs_f64();
                println!("[{completed}] {rps:.1} rps");
                batch_start = std::time::Instant::now();
                next_milestone = completed + 1000;
            }
        }
        index
    });

    // Error channel: workers send errors here, a dedicated task prints and tracks them
    let (err_tx, err_rx) = flume::unbounded::<ProbeError>();

    // Error reporting task: prints errors as they arrive, returns stats
    let error_task = rt.spawn(async move {
        let mut total_errors: usize = 0;
        let mut connection_errors: Vec<usize> = Vec::new();
        while let Ok(err) = err_rx.recv_async().await {
            total_errors += 1;
            match err {
                ProbeError::Http {
                    index,
                    request,
                    status,
                    content_type,
                    body,
                } => {
                    let is_text = content_type
                        .as_deref()
                        .is_some_and(|ct| ct.contains("json") || ct.contains("text"));
                    let body_str = if is_text {
                        String::from_utf8_lossy(&body).into_owned()
                    } else {
                        BASE64.encode(&body)
                    };
                    let preview = match body_str.char_indices().nth(512) {
                        Some((pos, _)) => &body_str[..pos],
                        None => &body_str,
                    };
                    eprintln!(
                        "[{index}] {:?} {} -> {status}: {preview}",
                        request.method, request.uri
                    );
                    log_request_details(&request);
                }
                ProbeError::Connection {
                    index,
                    request,
                    error,
                } => {
                    connection_errors.push(index);
                    eprintln!(
                        "[{index}] {:?} {} -> connection error: {error}",
                        request.method, request.uri
                    );
                    log_request_details(&request);
                }
            }
        }
        (total_errors, connection_errors)
    });

    // Spawn N async tasks that consume requests from the channel
    let tasks: Vec<_> = std::iter::repeat_n((rx, err_tx, abort), concurrency)
        .map(|(rx, err_tx, abort)| {
            let client = client.clone();
            let url = url.clone();
            rt.spawn(async move {
                while let Ok((index, request)) = rx.recv_async().await {
                    if abort.load(std::sync::atomic::Ordering::Relaxed) {
                        break;
                    }
                    match send_request(&client, &url, &request).await {
                        Ok(response) if response.status().is_success() => {
                            let _ = response.bytes().await;
                        }
                        Ok(response) => {
                            let status = response.status();
                            let content_type = response
                                .headers()
                                .get("content-type")
                                .and_then(|v| v.to_str().ok())
                                .map(|s| s.to_string());
                            let body = response
                                .bytes()
                                .await
                                .map(|b| b.to_vec().into_boxed_slice())
                                .unwrap_or_default();
                            let _ = err_tx.send(ProbeError::Http {
                                index,
                                request,
                                status,
                                content_type,
                                body,
                            });
                        }
                        Err(error) => {
                            abort.store(true, std::sync::atomic::Ordering::Relaxed);
                            let _ = err_tx.send(ProbeError::Connection {
                                index,
                                request,
                                error,
                            });
                            break;
                        }
                    }
                }
            })
        })
        .collect();

    for task in tasks {
        rt.block_on(task).expect("Task panicked");
    }

    let (total_errors, mut connection_errors) =
        rt.block_on(error_task).expect("Error task panicked");

    if connection_errors.len() > 1 {
        connection_errors.sort_unstable();
        eprintln!(
            "Got {} connection errors. Retry with --skip {} to narrow down.",
            connection_errors.len(),
            connection_errors[0]
        );
    }

    let last_index = reader_handle.join().expect("Reader thread panicked");
    let total = last_index - skip;
    println!(
        "Probed {total} requests: {} ok, {total_errors} failed",
        total.saturating_sub(total_errors)
    );
}

enum ProbeError {
    Http {
        index: usize,
        request: HttpRequest,
        status: reqwest::StatusCode,
        content_type: Option<String>,
        body: Box<[u8]>,
    },
    Connection {
        index: usize,
        request: HttpRequest,
        error: reqwest::Error,
    },
}

fn log_request_details(request: &HttpRequest) {
    for header in request.headers.iter() {
        eprintln!("  {header}");
    }
    if !request.body.is_empty() {
        let is_json = request
            .headers
            .iter()
            .any(|h| h.to_ascii_lowercase().contains("json"));
        if is_json {
            if let Ok(text) = std::str::from_utf8(&request.body) {
                eprintln!("  body: {text}");
            } else {
                eprintln!("  body (base64): {}", BASE64.encode(&request.body));
            }
        } else {
            eprintln!("  body (base64): {}", BASE64.encode(&request.body));
        }
    }
}

#[tokio::main(flavor = "multi_thread", worker_threads = 8)]
async fn run(
    url: String,
    playbook: PathBuf,
    max_concurrency: usize,
    additional_headers: Vec<String>,
) {
    let mut requests = Vec::new();
    let mut file = File::open(playbook).expect("Failed to open playbook file");
    let mut reader = std::io::BufReader::new(&mut file);
    while let Ok(request) = read_request(&mut reader) {
        requests.push(request);
    }
    let requests: Arc<[HttpRequest]> = Arc::from(requests);

    let client = reqwest::ClientBuilder::new()
        .default_headers(parse_headers(additional_headers))
        .build()
        .expect("Client::new()");

    // Try to send a single request to check if the server is up
    let _ = send_request(&client, &url, &requests[0])
        .await
        .expect("Failed to send a test request");

    // Doing concurrent requests via spawning tasks allows us to
    // - gradually increase the number of concurrent requests without pauses, thus keeping the server warm
    // - utilize more than one thread/core to avoid bottlenecks with sending requests
    let concurrency_levels = [4, 6, 8, 12, 16, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 128];
    let mut tasks = Vec::new();
    let (results_tx, results_rx) = flume::unbounded::<Option<std::num::NonZeroU32>>();
    let mut measure_cold_start = true;
    for concurrency in concurrency_levels
        .into_iter()
        .take_while(|c| *c <= max_concurrency)
    {
        // Gradually increase number of concurrent requests
        for task_idx in tasks.len()..concurrency {
            let client = client.clone();
            let url = url.clone();
            let requests = requests.clone();
            let results_tx = results_tx.clone();

            tasks.push(tokio::spawn(async move {
                // Avoid duplicate requests by cycling through the requests array
                let requests = requests
                    .iter()
                    .cycle()
                    .skip(task_idx)
                    .step_by(max_concurrency);
                for r in requests {
                    let start = std::time::Instant::now();
                    let result = send_request(&client, &url, r).await;

                    let elapsed_us = start.elapsed().as_micros();
                    let latency = if result.is_ok_and(|r| r.status().is_success()) {
                        Some(std::num::NonZeroU32::new(elapsed_us as u32).unwrap())
                    } else {
                        None
                    };

                    // Channel has been closed, stop sending results and exit the task
                    if results_tx.send(latency).is_err() {
                        break;
                    }
                }
            }));
        }

        // todo: remove copy&paste with logic below
        if measure_cold_start {
            measure_cold_start = false;

            let start = std::time::Instant::now();
            let mut successfull = 0;
            let mut total = 0;
            let mut latencies = Vec::new();
            let mut metric = Metric::default();
            while let Ok(latency) = results_rx.recv() {
                total += 1;
                if let Some(latency) = latency {
                    successfull += 1;
                    latencies.push(latency.get());
                }
                let elapsed = start.elapsed();
                if elapsed.as_secs() >= 5 {
                    metric.throughput = total as f64 / elapsed.as_secs_f64();
                    metric.success_rate = successfull as f64 / total as f64;
                    break;
                }
            }
            latencies.sort_unstable();
            metric.concurrency = concurrency as u16;
            metric.p50 = latencies[(latencies.len() as f64 * 0.50) as usize] as f64 / 1000.0;
            metric.p95 = latencies[(latencies.len() as f64 * 0.95) as usize] as f64 / 1000.0;
            metric.p99 = latencies[(latencies.len() as f64 * 0.99) as usize] as f64 / 1000.0;

            println!(
                "Cold start with concurrency {}: throughput {:.2}rps, success rate {:.2}, p50 {:.1}ms, p95 {:.1}ms, p99 {:.1}ms",
                metric.concurrency,
                metric.throughput,
                metric.success_rate,
                metric.p50,
                metric.p95,
                metric.p99
            );
        }

        // First 15s read all results and throw them away
        let start = std::time::Instant::now();
        while let Ok(_latency) = results_rx.recv() {
            if start.elapsed().as_secs() >= 15 {
                break;
            }
        }

        // Then read the results for 15s and count the success rate, throughput and p50, p95, p99 latency
        let start = std::time::Instant::now();
        let mut successfull = 0;
        let mut total = 0;
        let mut latencies = Vec::new();
        let mut metric = Metric::default();
        while let Ok(latency) = results_rx.recv() {
            total += 1;
            if let Some(latency) = latency {
                successfull += 1;
                latencies.push(latency.get());
            }
            let elapsed = start.elapsed();
            if elapsed.as_secs() >= 15 {
                metric.throughput = total as f64 / elapsed.as_secs_f64();
                metric.success_rate = successfull as f64 / total as f64;
                break;
            }
        }
        latencies.sort_unstable();
        metric.concurrency = concurrency as u16;
        metric.p50 = latencies[(latencies.len() as f64 * 0.50) as usize] as f64 / 1000.0;
        metric.p95 = latencies[(latencies.len() as f64 * 0.95) as usize] as f64 / 1000.0;
        metric.p99 = latencies[(latencies.len() as f64 * 0.99) as usize] as f64 / 1000.0;
        println!(
            "Concurrency {}: throughput {:.2}rps, success rate {:.2}, p50 {:.1}ms, p95 {:.1}ms, p99 {:.1}ms",
            metric.concurrency,
            metric.throughput,
            metric.success_rate,
            metric.p50,
            metric.p95,
            metric.p99
        );
    }

    // Close the channel to stop all tasks
    drop(results_tx);
    drop(results_rx);
    for t in tasks {
        t.await.expect("Task panicked");
    }
}

fn parse_headers(headers: Vec<String>) -> reqwest::header::HeaderMap {
    headers
        .into_iter()
        .filter_map(|h| {
            h.split_once(':').and_then(|(k, v)| {
                Some((
                    HeaderName::from_str(k.trim()).ok()?,
                    HeaderValue::from_str(v.trim()).ok()?,
                ))
            })
        })
        .collect()
}

fn read_request(reader: &mut impl std::io::BufRead) -> Result<HttpRequest> {
    let message = capnp::serialize_packed::read_message(reader, Default::default())?;
    let root = message
        .get_root::<playbook_capnp::http_request::Reader>()
        .context("Bad file format - no `HttpRequest`")?;

    Ok(HttpRequest {
        method: root.get_method().expect("Bad file format - no `method`"),
        uri: root
            .get_uri()
            .context("Bad file format - no `uri`")?
            .to_string()?
            .into(),
        headers: root
            .get_headers()
            .context("Bad file format - no `headers`")?
            .iter()
            .map(|h| h.unwrap().to_string().unwrap().into())
            .collect(),
        body: root
            .get_body()
            .context("Bad file format - no `body`")?
            .into(),
    })
}

fn write_request(request: &HttpRequest, mut writer: impl Write) -> Result<()> {
    let mut message = capnp::message::Builder::new_default();
    let mut request_builder = message.init_root::<playbook_capnp::http_request::Builder>();
    request_builder.set_method(request.method);
    request_builder.set_uri(&request.uri);
    request_builder.set_body(&request.body);
    request_builder
        .set_headers(request.headers.as_ref())
        .unwrap();

    Ok(capnp::serialize_packed::write_message(
        &mut writer,
        &message,
    )?)
}

async fn send_request(
    client: &reqwest::Client,
    base_url: &str,
    request: &HttpRequest,
) -> Result<reqwest::Response, reqwest::Error> {
    let method = match request.method {
        HttpMethod::Get => Method::GET,
        HttpMethod::Post => Method::POST,
        HttpMethod::Put => Method::PUT,
        HttpMethod::Delete => Method::DELETE,
        HttpMethod::Head => Method::HEAD,
        HttpMethod::Options => Method::OPTIONS,
        HttpMethod::Patch => Method::PATCH,
        HttpMethod::Trace => Method::TRACE,
    };

    client
        .request(method, format!("{}{}", base_url, &request.uri)) // URI always starts with '/'
        .headers(
            request
                .headers
                .iter()
                .map(|s| s.as_ref())
                .filter_map(|h| {
                    h.split_once(':').and_then(|(k, v)| {
                        Some((
                            HeaderName::from_str(k).ok()?,
                            HeaderValue::from_str(v).ok()?,
                        ))
                    })
                })
                .collect(),
        )
        .body(request.body.to_vec())
        .send()
        .await
}

#[derive(Default)]
struct Metric {
    concurrency: u16,
    throughput: f64,
    success_rate: f64,
    p50: f64,
    p95: f64,
    p99: f64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn read_write_request() {
        let requests = vec![
            HttpRequest {
                method: HttpMethod::Get,
                uri: "/test1".into(),
                headers: vec!["Accept:text/plain".into()].into(),
                body: Vec::new().into(),
            },
            HttpRequest {
                method: HttpMethod::Put,
                uri: "/test2".into(),
                headers: vec!["Content-Type:application/json".into()].into(),
                body: b"{\"key\":\"value\"}".to_vec().into(),
            },
        ];

        let mut buffer = Vec::new();
        for request in &requests {
            write_request(request, &mut buffer).expect("Failed to write request");
        }

        let mut reader = std::io::BufReader::new(buffer.as_slice());
        for original_request in &requests {
            let deserialized_request =
                read_request(&mut reader).expect("Failed to read request from buffer");

            assert_eq!(original_request.method, deserialized_request.method);
            assert_eq!(original_request.uri, deserialized_request.uri);
            assert_eq!(original_request.headers, deserialized_request.headers);
            assert_eq!(original_request.body, deserialized_request.body);
        }
    }
}
